### PR TITLE
Sort preference #20

### LINKED ISSUE #20: Sort lists
Implement an encoding preference that would allow to sort elemens in a RepSep encoder before encoding. This should enable to sort class members to put fields before methods.

### PR DESCRIPTION
**Pull request by nscarcella**
Another pretty little add-on to preferences. Please, tell me what you think @bossiernesto 

closes #20

### CODE REVIEW

**Comment by nscarcella** [comment]
Now what the hell do I need to do to make waffle realize this is freaking ticket #20?

**Comment by bossiernesto** [comment]
Let me see what happened over here,  i'll try to merge them or at least relate the tickets

**Comment by nscarcella** [comment]
@bossiernesto seems like you have to put the closes #n in the description of the PR. Damn waffle...

**Comment by bossiernesto** [comment]
Yes, i've done that on the description of the PR and now it's updated. Waffle will delay some moments but it's more a functionality of github issues.

**Comment by bossiernesto** [comment]
Looks good, i'm merging this PR. Thanks

**Pull request merged**
